const grid=document.querySelector('#coachGrid'),select=document.querySelector('#coachSelect'),dateInput=document.querySelector('#dateInput'),timeSelect=document.querySelector('#timeSelect'),note=document.querySelector('#availabilityNote'),modal=document.querySelector('#bookingModal'),form=document.querySelector('#bookingForm'),success=document.querySelector('#success');let coaches=[],filter='all';
async function api(path,options={}){const response=await fetch(`/api${path}`,{headers:{'Content-Type':'application/json'},...options});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Something went wrong.');return body}
function render(){const shown=filter==='all'?coaches:coaches.filter(c=>c.tags.split(',').includes(filter));grid.innerHTML=shown.length?shown.map(c=>`<article class="coach"><div class="coach-top" style="background:${c.color}"><span class="coach-tag">${c.specialty}</span><span class="coach-initial">${c.initial}</span></div><div class="coach-info"><div class="coach-name"><h3>${c.name}</h3><span>★ ${c.rating}</span></div><p class="coach-bio">${c.title}<br>${c.bio}</p><div class="coach-bottom"><div class="price">$${c.hourly_rate} <small>/ hour</small></div><button class="book" data-coach-id="${c.id}">Book session →</button></div></div></article>`).join(''):'<p class="loading">No coaches match that speciality yet.</p>'}
async function availability(){if(!select.value||!dateInput.value)return;timeSelect.disabled=true;note.textContent='Checking live availability…';try{const data=await api(`/availability?coachId=${select.value}&date=${dateInput.value}`);timeSelect.innerHTML=data.slots.length?data.slots.map(time=>`<option value="${time}">${time}</option>`).join(''):'<option value="">No times available</option>';note.textContent=data.slots.length?`${data.slots.length} times available.`:'This coach is fully booked on that date.'}catch(error){note.textContent=error.message;timeSelect.innerHTML='<option value="">Unavailable</option>'}timeSelect.disabled=false}
async function load(){try{coaches=await api('/coaches');select.innerHTML=coaches.map(c=>`<option value="${c.id}">${c.name} — $${c.hourly_rate}/hr</option>`).join('');render();availability()}catch(error){grid.innerHTML=`<p class="loading">Unable to load coaches: ${error.message}</p>`}}
function open(id){if(id)select.value=id;modal.classList.add('open');modal.setAttribute('aria-hidden','false');form.style.display='grid';success.classList.remove('show');availability();document.body.style.overflow='hidden'}function close(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
dateInput.min=new Date().toISOString().split('T')[0];dateInput.value=dateInput.min;select.addEventListener('change',availability);dateInput.addEventListener('change',availability);document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');filter=b.dataset.filter;render()}));document.addEventListener('click',e=>{if(e.target.matches('#openBooking,#heroBooking,#bottomBooking'))open();if(e.target.matches('.book'))open(e.target.dataset.coachId);if(e.target.matches('[data-close]'))close()});document.querySelector('#showAll').addEventListener('click',()=>{filter='all';document.querySelector('.filter.active').classList.remove('active');document.querySelector('[data-filter="all"]').classList.add('active');render()});
form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('button[type=submit]');button.disabled=true;try{const data=Object.fromEntries(new FormData(form));const result=await api('/bookings',{method:'POST',body:JSON.stringify({...data,coachId:Number(data.coach)})});form.style.display='none';document.querySelector('#successText').textContent=`${result.playerName}, your session with ${result.coachName} is booked for ${result.date} at ${result.time}. Confirmation will go to ${result.email}.`;success.classList.add('show')}catch(error){note.textContent=error.message;availability()}button.disabled=false});
const pieces={0:'♜',1:'♞',2:'♝',3:'♛',4:'♚',5:'♝',6:'♞',7:'♜',8:'♟',15:'♟',48:'♙',51:'♙',56:'♖',57:'♘',58:'♗',59:'♕',60:'♔',61:'♗',62:'♘',63:'♖'};document.querySelector('#chessBoard').innerHTML=Array.from({length:64},(_,i)=>`<div class="square ${(Math.floor(i/8)+i)%2?'dark':''}">${pieces[i]?`<span class="piece ${i<16?'black':''}">${pieces[i]}</span>`:''}</div>`).join('');if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');load();
