const TIMES = new Set(['10:00 AM', '1:00 PM', '4:00 PM', '7:00 PM']);
const json = (data, status = 200) => Response.json(data, { status, headers: { 'Cache-Control': 'no-store' } });
export default { async fetch(request, env) {
  const url = new URL(request.url);
  if (url.pathname === '/api/coaches' && request.method === 'GET') { const { results } = await env.DB.prepare('SELECT id,name,title,bio,hourly_rate,rating,specialty,tags,color,initial FROM coaches WHERE active=1 ORDER BY id').all(); return json(results); }
  if (url.pathname === '/api/availability' && request.method === 'GET') { const coachId = Number(url.searchParams.get('coachId')), date = url.searchParams.get('date'); if (!Number.isInteger(coachId) || !/^\d{4}-\d{2}-\d{2}$/.test(date || '')) return json({ error: 'A valid coach and date are required.' }, 400); const { results } = await env.DB.prepare("SELECT session_time FROM bookings WHERE coach_id=? AND session_date=? AND status!='cancelled'").bind(coachId, date).all(); return json({ slots: [...TIMES].filter(time => !results.some(row => row.session_time === time)) }); }
  if (url.pathname === '/api/bookings' && request.method === 'POST') { let data; try { data = await request.json(); } catch { return json({ error: 'Invalid booking details.' }, 400); } const playerName = String(data.name || '').trim(), email = String(data.email || '').trim().toLowerCase(), coachId = Number(data.coachId), date = String(data.date || ''), time = String(data.time || ''); if (!playerName || playerName.length > 80 || !/^\S+@\S+\.\S+$/.test(email) || !Number.isInteger(coachId) || !/^\d{4}-\d{2}-\d{2}$/.test(date) || !TIMES.has(time)) return json({ error: 'Please complete all booking details.' }, 400); const coach = await env.DB.prepare('SELECT name FROM coaches WHERE id=? AND active=1').bind(coachId).first(); if (!coach) return json({ error: 'That coach is unavailable.' }, 404); try { await env.DB.prepare("INSERT INTO bookings (coach_id,player_name,player_email,session_date,session_time,status) VALUES (?,?,?,?,?,'confirmed')").bind(coachId, playerName, email, date, time).run(); } catch (error) { if (String(error.message).includes('UNIQUE')) return json({ error: 'That time was just booked. Please choose another.' }, 409); throw error; } return json({ playerName, email, coachName: coach.name, date, time }, 201); }
  return env.ASSETS.fetch(request);
} };
